version: '3'
services:
  # config-server:
  #   image: lalossuarez/config-server
  #   ports:
  #     - 8888:8888
  reservation-service:
    container_name: reservation-service
    image: lalossuarez/reservation-service
    depends_on:
      - config-server
    ports:
      - 8000:8081
  eureka-server:
    container_name: eureka-server
    image: lalossuarez/eureka-server
    depends_on:
      - config-server
    ports:
      - 8761:8081