version: '2.1'
services:
  config-server:
    image: lalossuarez/config-server
    restart: always
    ports:
      - 8888:8888
  reservation-service:
    image: lalossuarez/reservation-service
    restart: always
    ports:
      - 8000:8000
  eureka-server:
    image: lalossuarez/eureka-server
    restart: always
    ports:
      - 8761:8761          