# Config for default profile (local development)
spring:
  profiles: default
  # define the destination to which the input MessageChannel should be bound
  # spring.cloud.stream.bindings.input=reservations
  cloud:
    stream:
      bindings:
        input:
          destination: reservations
          # ensures 1 node in a group gets message (point-to-point, not a broadcast)
          group: reservations-group
          # ensure that the Q is durable
          durableSubscription: true

#spring.profiles=cloud
#spring.eureka.instance.hostname=${APPLICATION_DOMAIN}
#spring.eureka.instance.nonSecurePort=80

message: This is configured as default profile 2
privateMessage: '{cipher}AQA4N82pzeLxqyYAT2+bHxS5VvldegWOUeyDIw0a0948eUgkIIuHsvoypMt1M3H4xR4ELDpHY8B9DRqu6WN6oMZNsU0yc9iQPKX7+S9DY1iDqsYkknwNnYYAukYCfP3dNGQJ0OQAHuTsm8tuY1/HOlAtn/aS5Ji+QBoTCu6235DSsEDroXFir5R36/C3KxcGSf/jvgaacDWHhOFitRuCX+W5q9m3uFs07akmoqu1TBCMvi+RUXTUD95Vi9PlmfqnhVcz7McTk1HqIEpfo7eBlZVt+hIENh51n+Ij9OfY6sgGjk/5R1F06SPya2dfewtzOHv3YpzY1fdrXFHLzvtJY31de7HWhuHo5QhVn1boZZuBVQJkAfvfJTzdJAMqIxa+RdwZAaUlIE3CUijmBTNtgZdm'

# Comma separated values for all the eureka's servers avialable
#eureka.client.serviceUrl.defaultZone=${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 2
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

server:
    port: ${PORT:8000}

# Config for docker profile (deploying using docker)
---
spring:
  profiles: docker
  cloud:
    stream:
      bindings:
        input:
          destination: reservations
          group: reservations-group
          durableSubscription: true

message: This is configured as docker profile
privateMessage: '{cipher}AQA4N82pzeLxqyYAT2+bHxS5VvldegWOUeyDIw0a0948eUgkIIuHsvoypMt1M3H4xR4ELDpHY8B9DRqu6WN6oMZNsU0yc9iQPKX7+S9DY1iDqsYkknwNnYYAukYCfP3dNGQJ0OQAHuTsm8tuY1/HOlAtn/aS5Ji+QBoTCu6235DSsEDroXFir5R36/C3KxcGSf/jvgaacDWHhOFitRuCX+W5q9m3uFs07akmoqu1TBCMvi+RUXTUD95Vi9PlmfqnhVcz7McTk1HqIEpfo7eBlZVt+hIENh51n+Ij9OfY6sgGjk/5R1F06SPya2dfewtzOHv3YpzY1fdrXFHLzvtJY31de7HWhuHo5QhVn1boZZuBVQJkAfvfJTzdJAMqIxa+RdwZAaUlIE3CUijmBTNtgZdm'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 2
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

server:
    port: ${PORT:8000}