# Config for default profile (local development)
server:
  port: 8888

spring:
  profiles: default
  cloud:
    config:
      server:
        git:
          # uri: ${user.home}/spring-config-repo
          uri: https://github.com/lalosuarez/spring-cloud-config-demo

security:
  basic:
    enabled: true
  user:
    name: configserver
    password: configserver1

# Config for docker profile (deploying using docker)
---
server:
  port: 8888

spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lalosuarez/spring-cloud-config-demo

security:
  basic:
    enabled: true
  user:
    name: configserver
    password: configserver1